import index from "./globals.css";
import Footer from "@/Components/Footer";
import Navbar from "@/Components/Navbar";

import { Bricolage_Grotesque } from "next/font/google";

const bricolage = Bricolage_Grotesque({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Babushka",
  description: "Generated by Concepto Hexágono",
  keywords: " Muñecas rusas, artesanías y juguetes."
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" className="!scroll-smooth mx-auto container bg-[#d87f7f]">
      <body className={bricolage.className}>
        <Navbar />
        {children} <Footer />
      </body>
    </html>
  );
}
